# This file was generated by GoReleaser. DO NOT EDIT.
cask "mb-cli" do
  name "mb-cli"
  desc "mb-cli - A read-only CLI for the Metabase API"
  homepage "https://github.com/andreagrandi/mb-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mb-cli"

  on_macos do
    on_intel do
      url "https://github.com/andreagrandi/mb-cli/releases/download/v#{version}/mb-cli_Darwin_x86_64.tar.gz"
      sha256 "4fa5d35552c0a62bc01d077eb2c6b2e6e8b77fde7a4ab451bf8952344b1d484e"
    end
    on_arm do
      url "https://github.com/andreagrandi/mb-cli/releases/download/v#{version}/mb-cli_Darwin_arm64.tar.gz"
      sha256 "97c6ca1e50fdf871ad72339813ebb1dcc49e61aa951861740cb7cfb90e3fd6e4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andreagrandi/mb-cli/releases/download/v#{version}/mb-cli_Linux_x86_64.tar.gz"
      sha256 "cbd73dad61ef8c9b3646f4b1562b3ad366638f42aa0618ef61074978fd9a5739"
    end
    on_arm do
      url "https://github.com/andreagrandi/mb-cli/releases/download/v#{version}/mb-cli_Linux_arm64.tar.gz"
      sha256 "2965b17312a8d82c29dd1b3b6d480819f2c25ceef7473f7a2e701350afcbccee"
    end
  end

  # No zap stanza required
end
