# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logbasset < Formula
  desc "LogBasset - A tool for querying and tailing logs"
  homepage "https://github.com/andreagrandi/logbasset"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/logbasset/releases/download/v0.2.1/logbasset_Darwin_x86_64.tar.gz"
      sha256 "ed694cf4ece93bbbe6046aa9ef5a904ec3e67e8acdcde76872b8fdbd5337465d"

      def install
        bin.install "logbasset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/logbasset/releases/download/v0.2.1/logbasset_Darwin_arm64.tar.gz"
      sha256 "a601f0c14900525c0b47ec8f021367f0cc989a05d985e09b2d7c9ca16de9f37e"

      def install
        bin.install "logbasset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/logbasset/releases/download/v0.2.1/logbasset_Linux_x86_64.tar.gz"
      sha256 "af03727dff77c77619c3a7662171ef3d40b0554e2c7251f5ba45bc85df3fd4b7"
      def install
        bin.install "logbasset"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/logbasset/releases/download/v0.2.1/logbasset_Linux_arm64.tar.gz"
      sha256 "62fffe683892da9782ba993cc0072e75b4e89c4bb8d66a2087ff67a04e86c2f4"
      def install
        bin.install "logbasset"
      end
    end
  end

  test do
    system "#{bin}/logbasset --version"
  end
end
