# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MbCli < Formula
  desc "mb-cli - A read-only CLI for the Metabase API"
  homepage "https://github.com/andreagrandi/mb-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.2.0/mb-cli_Darwin_x86_64.tar.gz"
      sha256 "90515de8f82bea5ffdd3567fcbaa23ade0a7db5179d415138dc1d40ea852b6a8"

      define_method(:install) do
        bin.install "mb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.2.0/mb-cli_Darwin_arm64.tar.gz"
      sha256 "545498a2f62a677a1cd8b6b64322275af36aa238091d6135211c72bfc2069527"

      define_method(:install) do
        bin.install "mb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.2.0/mb-cli_Linux_x86_64.tar.gz"
      sha256 "28e217edca174aff83607850233880ef98ad4899268ad072f14d64d7518c6c2a"
      define_method(:install) do
        bin.install "mb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.2.0/mb-cli_Linux_arm64.tar.gz"
      sha256 "d36a87d5700361a37a301de96dba352d65bdc5019d81ead4f13f0bfcee064c63"
      define_method(:install) do
        bin.install "mb-cli"
      end
    end
  end

  test do
    system "#{bin}/mb-cli --version"
  end
end
