# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MbCli < Formula
  desc "mb-cli - A read-only CLI for the Metabase API"
  homepage "https://github.com/andreagrandi/mb-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.1.1/mb-cli_Darwin_x86_64.tar.gz"
      sha256 "2e7c5d64e24227cd043c96434a945b2f8c0d2113b47f473c1dfd55f06e0b5ef5"

      define_method(:install) do
        bin.install "mb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.1.1/mb-cli_Darwin_arm64.tar.gz"
      sha256 "16fe119694385fa936e16999ea5557a65008f9c79b480fbefe4171074bddecc1"

      define_method(:install) do
        bin.install "mb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.1.1/mb-cli_Linux_x86_64.tar.gz"
      sha256 "f8340c1c808f619c28f715e4f7f249f256268dfa46a469f22051a475708bb741"
      define_method(:install) do
        bin.install "mb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mb-cli/releases/download/v0.1.1/mb-cli_Linux_arm64.tar.gz"
      sha256 "896893725c546c84da552a747d6360ea3ccc1f26c556537d2899e126e83a407d"
      define_method(:install) do
        bin.install "mb-cli"
      end
    end
  end

  test do
    system "#{bin}/mb-cli --version"
  end
end
