# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpWire < Formula
  desc "Install and configure MCP servers across AI coding tools"
  homepage "https://github.com/andreagrandi/mcp-wire"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.3.0/mcp-wire_Darwin_x86_64.tar.gz"
      sha256 "4e1f05d4b84c745ff5342b9eb720224a8a79b5d6f4066bc2ead06b1b87b9fba9"

      define_method(:install) do
        bin.install "mcp-wire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.3.0/mcp-wire_Darwin_arm64.tar.gz"
      sha256 "1b5170e7df8792105b57fa9fa89ea2b70f09092ca3d3ff5053f74613d59f7241"

      define_method(:install) do
        bin.install "mcp-wire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.3.0/mcp-wire_Linux_x86_64.tar.gz"
      sha256 "8fbbc1f95e84758e8488afefeed510fc2322b258351d746f8a896fb7a2a867c3"
      define_method(:install) do
        bin.install "mcp-wire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.3.0/mcp-wire_Linux_arm64.tar.gz"
      sha256 "b15e8af7ba0d4ee7923332f2dd5ade0e9bdde2e7c8e072a1a09d006a633aa425"
      define_method(:install) do
        bin.install "mcp-wire"
      end
    end
  end

  test do
    system "#{bin}/mcp-wire --version"
  end
end
