# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpWire < Formula
  desc "Install and configure MCP servers across AI coding tools"
  homepage "https://github.com/andreagrandi/mcp-wire"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.1.0/mcp-wire_Darwin_x86_64.tar.gz"
      sha256 "7a6319c84ae0f5c3ffa0249be34ad5c60d3cc187a7bdc538262e62a9c862c51b"

      def install
        bin.install "mcp-wire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.1.0/mcp-wire_Darwin_arm64.tar.gz"
      sha256 "585bc854d6b8bffaaecd1aa4dc10ddc76ad46125b2bf644a8e9d9549970be2ff"

      def install
        bin.install "mcp-wire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.1.0/mcp-wire_Linux_x86_64.tar.gz"
      sha256 "005f28e50278611ccba405793d1aa5fe52420df29b8251665d37a300ca4bd75e"
      def install
        bin.install "mcp-wire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/mcp-wire/releases/download/v0.1.0/mcp-wire_Linux_arm64.tar.gz"
      sha256 "e75a214bfe4fb8264c705bf2d16a0453c5ed0f882f4f0594f6c6b48d0a792ae3"
      def install
        bin.install "mcp-wire"
      end
    end
  end

  test do
    system "#{bin}/mcp-wire --version"
  end
end
