# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentire < Formula
  desc "Sentire - A CLI tool for the Sentry API"
  homepage "https://github.com/andreagrandi/sentire"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.2.0/sentire_Darwin_x86_64.tar.gz"
      sha256 "81855b87f9400ebc9596b94da7b08c960e95b15ecb94e7b3941e9774e92ddba0"

      def install
        bin.install "sentire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.2.0/sentire_Darwin_arm64.tar.gz"
      sha256 "69a58af87d37557c8dede66461dd737a7bdc159fa1ad41334e9c8486ff33df56"

      def install
        bin.install "sentire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.2.0/sentire_Linux_x86_64.tar.gz"
      sha256 "0cd48d76b7fbfbb32db73ad0f90c90cbfa4640647a121618e509ae2723118719"
      def install
        bin.install "sentire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.2.0/sentire_Linux_arm64.tar.gz"
      sha256 "547e45d841c9f18848a9e9fbc4d7bcb9172fff31b5594e1516ba4c92cb3caa93"
      def install
        bin.install "sentire"
      end
    end
  end

  test do
    system "#{bin}/sentire --version"
  end
end
