# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sentire < Formula
  desc "Sentire - A CLI tool for the Sentry API"
  homepage "https://github.com/andreagrandi/sentire"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.1.0/sentire_Darwin_x86_64.tar.gz"
      sha256 "128b88a8a30a2d9cb9fb7f19378746019493e33e32d8709bb198d53954f7d7dc"

      def install
        bin.install "sentire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.1.0/sentire_Darwin_arm64.tar.gz"
      sha256 "6cf7f6dd0b2205ce39c6f609161c56062549bde98a69cdf3e2b6a9352e72a735"

      def install
        bin.install "sentire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.1.0/sentire_Linux_x86_64.tar.gz"
      sha256 "3ef762db8a6f31c2ce1300065e4ee451fd30bfdaadfc1a2e89e67bf7be0e52ed"
      def install
        bin.install "sentire"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/andreagrandi/sentire/releases/download/v0.1.0/sentire_Linux_arm64.tar.gz"
      sha256 "7e50c441230d669940a0e29df30b6fd568cc2d52a1066122520cef811b425a7c"
      def install
        bin.install "sentire"
      end
    end
  end

  test do
    system "#{bin}/sentire --version"
  end
end
